-- local builtin = require('telescope.builtin')
-- all keymaps are handled by which key in whichkey.lua
-- vim.keymap.set('n', '<leader>pf', builtin.find_files, {}) -- respecting .gitignore
-- vim.keymap.set('n', '<C-p>', builtin.git_files, {})
-- vim.keymap.set('n', '<leader>ps', function()
-- builtin.grep_string( {search = vim.fn.input("grep: ") });
-- end)
